## 读取数据

In [9]:
import pandas as pd

In [12]:

original_date= pd.read_csv(r'C:\Users\Administrator\Desktop\数据分析\五粮液股票数据.csv', encoding='gbk')

In [13]:
original_date.head()

,股票代码,交易日期,开盘价,最高价,最低价,收盘价,昨收价,涨跌额,涨跌幅,成交量（手）,成交额（千元）
0,000858.SZ,20180920,64.40,64.85,64.03,64.39,64.44,-0.05,-0.0776,164165.71,1056728.297
1,000858.SZ,20180919,62.99,65.53,62.90,64.44,63.21,1.23,1.9459,411364.31,2653606.009
2,000858.SZ,20180918,61.62,63.60,61.01,63.21,61.86,1.35,2.1823,263861.24,1647393.657
3,000858.SZ,20180917,61.40,62.56,61.03,61.86,61.53,0.33,0.5363,235508.59,1458775.764
4,000858.SZ,20180914,60.45,62.16,59.70,61.53,59.98,1.55,2.5842,294960.29,1800648.312

## 评估数据整齐度

In [14]:
original_date.sample(10)

,股票代码,交易日期,开盘价,最高价,最低价,收盘价,昨收价,涨跌额,涨跌幅,成交量（手）,成交额（千元）
1457,000858.SZ,20120925,32.60,33.26,32.45,32.86,32.65,0.21,0.64,114109.55,3.758279e+05
3068,000858.SZ,20060220,8.11,8.11,8.11,8.11,8.11,0.00,0.00,0.00,0.000000e+00
1207,000858.SZ,20131018,18.20,18.29,17.93,18.03,18.19,-0.16,-0.88,139404.30,2.518691e+05
2310,000858.SZ,20090330,15.71,15.88,15.57,15.61,15.69,-0.08,-0.51,348909.18,5.485742e+05
3145,000858.SZ,20051021,7.01,7.02,6.93,6.97,7.01,-0.04,-0.57,34503.17,2.407648e+04
2814,000858.SZ,20070307,23.70,24.67,23.60,24.30,23.68,0.62,2.62,317960.64,7.681171e+05
396,000858.SZ,20170214,38.70,38.90,38.30,38.66,38.58,0.08,0.21,168320.98,6.500702e+05
2128,000858.SZ,20091223,29.50,30.28,29.36,29.97,28.95,1.02,3.52,456876.47,1.363914e+06
3789,000858.SZ,20030225,11.78,11.95,11.78,11.89,11.77,0.12,1.02,7483.55,8.877142e+03
1667,000858.SZ,20111117,35.80,36.43,35.74,36.00,36.29,-0.29,-0.80,165800.38,5.987809e+05

## 评估数据干净程度

In [15]:
original_date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3821 entries, 0 to 3820
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   股票代码     3821 non-null   object
 1   交易日期     3821 non-null   int64
 2   开盘价      3821 non-null   float64
 3   最高价      3821 non-null   float64
 4   最低价      3821 non-null   float64
 5   收盘价      3821 non-null   float64
 6   昨收价      3821 non-null   float64
 7   涨跌额      3821 non-null   float64
 8   涨跌幅      3821 non-null   float64
 9   成交量（手）   3821 non-null   float64
 10  成交额（千元）  3821 non-null   float64
dtypes: float64(9), int64(1), object(1)
memory usage: 328.5+ KB

### 评估数据缺失值

In [16]:
original_date[original_date["最高价"].isnull()]

Empty DataFrame
Columns: [股票代码, 交易日期, 开盘价, 最高价, 最低价, 收盘价, 昨收价, 涨跌额, 涨跌幅, 成交量（手）, 成交额（千元）]
Index: []

In [17]:
original_date["最高价"].value_counts()

最高价
25.73    63
8.11     19
8.36     14
20.80    12
36.00     9
         ..
11.38     1
11.20     1
66.18     1
64.51     1
64.50     1
Name: count, Length: 2313, dtype: int64

In [18]:
original_date.describe()

,交易日期,开盘价,最高价,最低价,收盘价,昨收价,涨跌额,涨跌幅,成交量（手）,成交额（千元）
count,3.821000e+03,3821.000000,3821.000000,3821.000000,3821.000000,3821.000000,3821.000000,3821.000000,3.821000e+03,3.821000e+03
mean,2.010449e+07,26.409798,26.871230,25.994214,26.440521,26.419914,0.020607,0.111864,2.430039e+05,7.222158e+05
std,4.541083e+04,16.507952,16.795185,16.226416,16.525752,16.516516,0.760788,2.439032,2.179887e+05,7.497783e+05
min,2.003010e+07,6.030000,6.080000,5.950000,6.020000,6.020000,-5.420000,-19.500000,0.000000e+00,0.000000e+00
25%,2.006121e+07,14.240000,14.500000,13.960000,14.240000,14.230000,-0.240000,-1.160000,1.063391e+05,1.703864e+05
50%,2.010112e+07,24.350000,24.940000,23.910000,24.440000,24.400000,0.000000,0.000000,1.966961e+05,5.155916e+05
75%,2.014103e+07,34.030000,34.510000,33.600000,34.070000,34.050000,0.260000,1.250000,3.153220e+05,9.911795e+05
max,2.018092e+07,91.200000,93.180000,90.680000,91.750000,91.750000,5.250000,10.020000,2.265968e+06,5.572737e+06

In [19]:
clean_date = original_date.copy()

In [20]:
clean_date.head()

,股票代码,交易日期,开盘价,最高价,最低价,收盘价,昨收价,涨跌额,涨跌幅,成交量（手）,成交额（千元）
0,000858.SZ,20180920,64.40,64.85,64.03,64.39,64.44,-0.05,-0.0776,164165.71,1056728.297
1,000858.SZ,20180919,62.99,65.53,62.90,64.44,63.21,1.23,1.9459,411364.31,2653606.009
2,000858.SZ,20180918,61.62,63.60,61.01,63.21,61.86,1.35,2.1823,263861.24,1647393.657
3,000858.SZ,20180917,61.40,62.56,61.03,61.86,61.53,0.33,0.5363,235508.59,1458775.764
4,000858.SZ,20180914,60.45,62.16,59.70,61.53,59.98,1.55,2.5842,294960.29,1800648.312