## 读取数据

In [1]:
import pandas as pd

In [2]:

original_date= pd.read_csv(r'C:\Users\Administrator\Desktop\数据分析\五粮液股票数据.csv', encoding='gbk')

In [3]:
original_date.head()

,股票代码,交易日期,开盘价,最高价,最低价,收盘价,昨收价,涨跌额,涨跌幅,成交量（手）,成交额（千元）
0,000858.SZ,20180920,64.40,64.85,64.03,64.39,64.44,-0.05,-0.0776,164165.71,1056728.297
1,000858.SZ,20180919,62.99,65.53,62.90,64.44,63.21,1.23,1.9459,411364.31,2653606.009
2,000858.SZ,20180918,61.62,63.60,61.01,63.21,61.86,1.35,2.1823,263861.24,1647393.657
3,000858.SZ,20180917,61.40,62.56,61.03,61.86,61.53,0.33,0.5363,235508.59,1458775.764
4,000858.SZ,20180914,60.45,62.16,59.70,61.53,59.98,1.55,2.5842,294960.29,1800648.312

In [4]:
original_date.head()

,股票代码,交易日期,开盘价,最高价,最低价,收盘价,昨收价,涨跌额,涨跌幅,成交量（手）,成交额（千元）
0,000858.SZ,20180920,64.40,64.85,64.03,64.39,64.44,-0.05,-0.0776,164165.71,1056728.297
1,000858.SZ,20180919,62.99,65.53,62.90,64.44,63.21,1.23,1.9459,411364.31,2653606.009
2,000858.SZ,20180918,61.62,63.60,61.01,63.21,61.86,1.35,2.1823,263861.24,1647393.657
3,000858.SZ,20180917,61.40,62.56,61.03,61.86,61.53,0.33,0.5363,235508.59,1458775.764
4,000858.SZ,20180914,60.45,62.16,59.70,61.53,59.98,1.55,2.5842,294960.29,1800648.312

## 评估数据整齐度

In [5]:
original_date.sample(10)

,股票代码,交易日期,开盘价,最高价,最低价,收盘价,昨收价,涨跌额,涨跌幅,成交量（手）,成交额（千元）
359,000858.SZ,20170410,42.65,42.66,41.42,41.66,42.69,-1.03,-2.41,260676.13,1.089896e+06
1017,000858.SZ,20140725,19.51,19.74,19.35,19.63,19.50,0.13,0.67,187121.20,3.656083e+05
1695,000858.SZ,20111010,36.28,36.42,35.60,35.66,36.30,-0.64,-1.76,109340.75,3.930941e+05
3695,000858.SZ,20030716,10.43,10.64,10.40,10.54,10.42,0.12,1.15,151549.30,1.597947e+05
567,000858.SZ,20160530,28.76,28.97,28.33,28.80,28.86,-0.06,-0.21,149459.27,4.285397e+05
848,000858.SZ,20150408,24.20,24.76,23.81,24.17,24.18,-0.01,-0.04,1028817.07,2.501701e+06
927,000858.SZ,20141208,19.55,20.32,19.21,20.23,19.63,0.60,3.06,898422.87,1.785139e+06
370,000858.SZ,20170322,43.01,44.20,42.80,43.96,43.38,0.58,1.34,381447.01,1.657890e+06
1016,000858.SZ,20140728,19.66,20.35,19.66,20.02,19.63,0.39,1.99,269386.01,5.393658e+05
2693,000858.SZ,20070830,35.00,35.38,34.41,34.88,34.48,0.40,1.16,218927.11,7.633302e+05

## 评估数据干净程度

In [6]:
original_date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3821 entries, 0 to 3820
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   股票代码     3821 non-null   object
 1   交易日期     3821 non-null   int64
 2   开盘价      3821 non-null   float64
 3   最高价      3821 non-null   float64
 4   最低价      3821 non-null   float64
 5   收盘价      3821 non-null   float64
 6   昨收价      3821 non-null   float64
 7   涨跌额      3821 non-null   float64
 8   涨跌幅      3821 non-null   float64
 9   成交量（手）   3821 non-null   float64
 10  成交额（千元）  3821 non-null   float64
dtypes: float64(9), int64(1), object(1)
memory usage: 328.5+ KB

### 评估数据缺失值

In [7]:
original_date[original_date["最高价"].isnull()]

Empty DataFrame
Columns: [股票代码, 交易日期, 开盘价, 最高价, 最低价, 收盘价, 昨收价, 涨跌额, 涨跌幅, 成交量（手）, 成交额（千元）]
Index: []

In [8]:
original_date["最高价"].value_counts()

最高价
25.73    63
8.11     19
8.36     14
20.80    12
36.00     9
         ..
11.38     1
11.20     1
66.18     1
64.51     1
64.50     1
Name: count, Length: 2313, dtype: int64

In [9]:
original_date.describe()

,交易日期,开盘价,最高价,最低价,收盘价,昨收价,涨跌额,涨跌幅,成交量（手）,成交额（千元）
count,3.821000e+03,3821.000000,3821.000000,3821.000000,3821.000000,3821.000000,3821.000000,3821.000000,3.821000e+03,3.821000e+03
mean,2.010449e+07,26.409798,26.871230,25.994214,26.440521,26.419914,0.020607,0.111864,2.430039e+05,7.222158e+05
std,4.541083e+04,16.507952,16.795185,16.226416,16.525752,16.516516,0.760788,2.439032,2.179887e+05,7.497783e+05
min,2.003010e+07,6.030000,6.080000,5.950000,6.020000,6.020000,-5.420000,-19.500000,0.000000e+00,0.000000e+00
25%,2.006121e+07,14.240000,14.500000,13.960000,14.240000,14.230000,-0.240000,-1.160000,1.063391e+05,1.703864e+05
50%,2.010112e+07,24.350000,24.940000,23.910000,24.440000,24.400000,0.000000,0.000000,1.966961e+05,5.155916e+05
75%,2.014103e+07,34.030000,34.510000,33.600000,34.070000,34.050000,0.260000,1.250000,3.153220e+05,9.911795e+05
max,2.018092e+07,91.200000,93.180000,90.680000,91.750000,91.750000,5.250000,10.020000,2.265968e+06,5.572737e+06

In [10]:
clean_date = original_date.copy()

In [11]:
clean_date.head()

,股票代码,交易日期,开盘价,最高价,最低价,收盘价,昨收价,涨跌额,涨跌幅,成交量（手）,成交额（千元）
0,000858.SZ,20180920,64.40,64.85,64.03,64.39,64.44,-0.05,-0.0776,164165.71,1056728.297
1,000858.SZ,20180919,62.99,65.53,62.90,64.44,63.21,1.23,1.9459,411364.31,2653606.009
2,000858.SZ,20180918,61.62,63.60,61.01,63.21,61.86,1.35,2.1823,263861.24,1647393.657
3,000858.SZ,20180917,61.40,62.56,61.03,61.86,61.53,0.33,0.5363,235508.59,1458775.764
4,000858.SZ,20180914,60.45,62.16,59.70,61.53,59.98,1.55,2.5842,294960.29,1800648.312

In [14]:
# 计算“价格”列的平均值
average_price = original_date['最高价'].mean()
print(f"平均价格: {average_price}")

平均价格: 26.87123004449097

In [20]:
filtered_date = original_date[original_date["最高价"]>10]

In [21]:
print(filtered_date)

           股票代码      交易日期    开盘价    最高价    最低价    收盘价    昨收价   涨跌额     涨跌幅  \
0     000858.SZ  20180920  64.40  64.85  64.03  64.39  64.44 -0.05 -0.0776
1     000858.SZ  20180919  62.99  65.53  62.90  64.44  63.21  1.23  1.9459
2     000858.SZ  20180918  61.62  63.60  61.01  63.21  61.86  1.35  2.1823
3     000858.SZ  20180917  61.40  62.56  61.03  61.86  61.53  0.33  0.5363
4     000858.SZ  20180914  60.45  62.16  59.70  61.53  59.98  1.55  2.5842
...         ...       ...    ...    ...    ...    ...    ...   ...     ...
3816  000858.SZ  20030108  11.12  11.37  11.10  11.35  11.12  0.23  2.0700
3817  000858.SZ  20030107  11.10  11.28  11.10  11.12  11.23 -0.11 -0.9800
3818  000858.SZ  20030106  11.18  11.28  11.00  11.23  11.18  0.05  0.4500
3819  000858.SZ  20030103  11.14  11.30  11.11  11.18  11.15  0.03  0.2700
3820  000858.SZ  20030102  11.45  11.46  11.10  11.15  11.59 -0.44 -3.8000

         成交量（手）       成交额（千元）
0     164165.71  1.056728e+06
1     411364.31  2.653606e+06
2     263861.24  1.647394e+06
3     235508.59  1.458776e+06
4     294960.29  1.800648e+06
...         ...           ...
3816    3722.07  4.183312e+03
3817    3861.13  4.303665e+03
3818    4205.45  4.692610e+03
3819    4821.27  5.379806e+03
3820    6501.25  7.293120e+03

[3245 rows x 11 columns]

In [25]:
# 将筛选后的数据保存为新的CSV文件
filtered_date.to_csv(r'C:\Users\Administrator\Desktop\数据分析\筛选后的五粮液股票数据.csv', index=False, encoding='gbk')

In [1]:
# 获取输入字符串
s = input("请输入一个字符串：")

# 初始化计数器
uppercase_count = 0
lowercase_count = 0
digit_count = 0

# 遍历字符串
for char in s:
    if char.isupper():
        uppercase_count += 1
    elif char.islower():
        lowercase_count += 1
    elif char.isdigit():
        digit_count += 1

# 输出结果
print(f"大写字母个数: {uppercase_count}")
print(f"小写字母个数: {lowercase_count}")
print(f"数字个数: {digit_count}")

请输入一个字符串： asdnkKBJdsb

大写字母个数: 3
小写字母个数: 8
数字个数: 0

In [3]:
def extract_birthdate(id_number):
    """
    从身份证号码中提取出生年月日。

    参数:
        id_number (str): 身份证号码，长度应为18位或15位。

    返回:
        str: 出生日期，格式为 YYYY-MM-DD。
    """
    if len(id_number) == 18:
        birthdate_str = id_number[6:14]  # 第7到14位
        year = birthdate_str[0:4]
        month = birthdate_str[4:6]
        day = birthdate_str[6:8]
    elif len(id_number) == 15:
        birthdate_str = id_number[6:12]  # 第7到12位
        year = "19" + birthdate_str[0:2]
        month = birthdate_str[2:4]
        day = birthdate_str[4:6]
    else:
        return "无效的身份证号码长度。"

    # 验证日期的有效性
    try:
        from datetime import datetime
        birthdate = datetime(int(year), int(month), int(day))
        return birthdate.strftime("%Y-%m-%d")
    except ValueError:
        return "身份证号码中的出生日期无效。"

# 示例用法
if __name__ == "__main__":
    id_num = input("请输入身份证号码：").strip()
    birthdate = extract_birthdate(id_num)
    print(f"出生日期：{birthdate}")

请输入身份证号码： 440152200412064569

出生日期：2004-12-06

In [4]:
import random
import re

# 定义姓氏字符串，使用正则表达式去除所有非汉字字符
first = '''赵钱孙李，周吴郑王。冯陈褚卫，蒋沈韩杨。朱秦尤许，何吕施张。'''
# 提取所有汉字字符作为姓氏列表
surnames = re.findall(r'[\u4e00-\u9fff]', first)

# 定义名字字符集
# 这里提供了一些常用的名字字符，你可以根据需要自行添加
second = '''伟刚勇毅俊峰强军平保东文辉力明永健世广志义兴良海山'''
# 将名字字符转换为列表
given_names = list(second)

def generate_random_name():
    """
    生成一个随机的三字中文姓名。
    
    返回:
        str: 生成的姓名
    """
    # 随机选择一个姓氏
    surname = random.choice(surnames)
    
    # 随机选择两个名字字符
    given_name = ''.join(random.choices(given_names, k=2))
    
    # 组合成完整的姓名
    full_name = surname + given_name
    return full_name

# 示例输出
if __name__ == "__main__":
    random_name = generate_random_name()
    print(f"随机生成的姓名是：{random_name}")

随机生成的姓名是：沈明东

In [6]:
import re

def mask_birthdate(id_number):
    """
    将身份证号码中的出生年月信息替换为星号，并进行基本格式验证。
    
    参数:
        id_number (str): 身份证号码，长度应为15位或18位。
    
    返回:
        str: 处理后的身份证号码，出生年月部分用星号替换，或错误提示。
    """
    id_number = id_number.strip()
    length = len(id_number)
    
    if length == 18:
        pattern = r'^\d{17}[\dXx]$'
        birthdate = id_number[6:14]
    elif length == 15:
        pattern = r'^\d{15}$'
        birthdate = id_number[6:12]
    else:
        return "无效的身份证号码长度。"
    
    if not re.match(pattern, id_number):
        return "身份证号码格式不正确。"
    
    # 简单的出生日期验证
    try:
        if length == 18:
            from datetime import datetime
            datetime.strptime(birthdate, "%Y%m%d")
        elif length == 15:
            from datetime import datetime
            datetime.strptime("19" + birthdate, "%Y%m%d")
    except ValueError:
        return "身份证号码中的出生日期无效。"
    
    # 替换出生年月
    if length == 18:
        masked_id = id_number[:6] + '*' * 8 + id_number[14:]
    else:
        masked_id = id_number[:6] + '*' * 6 + id_number[12:]
    
    return masked_id

# 示例用法
if __name__ == "__main__":
    id_num = input("请输入身份证号码：").strip()
    masked_id = mask_birthdate(id_num)
    print(f"处理后的身份证号码：{masked_id}")

请输入身份证号码： 440182200511051287

处理后的身份证号码：440182********1287

In [7]:
import json
import os

class UsernameManager:
    def __init__(self, filepath="usernames.json"):
        self.filepath = filepath
        self.usernames = set()
        self._load_usernames()
    
    def _load_usernames(self):
        if os.path.exists(self.filepath):
            with open(self.filepath, 'r', encoding='utf-8') as f:
                data = json.load(f)
                self.usernames = set(data)
    
    def _save_usernames(self):
        with open(self.filepath, 'w', encoding='utf-8') as f:
            json.dump(list(self.usernames), f, ensure_ascii=False, indent=4)
    
    def add_username(self, username):
        normalized = self._normalize(username)
        if normalized in self.usernames:
            return False
        self.usernames.add(normalized)
        self._save_usernames()
        return True
    
    def is_username_taken(self, username):
        normalized = self._normalize(username)
        return normalized in self.usernames
    
    def _normalize(self, username):
        return username.lower().strip()

# 示例用法同上

In [ ]:
# 会员名管理类
class UsernameManager:
    def __init__(self):
        # 使用集合存储标准化后的会员名，集合的查找时间复杂度为O(1)
        self.usernames = set()
    
    def add_username(self, username):
        """
        尝试添加一个新的会员名。

        参数:
            username (str): 用户输入的会员名。

        返回:
            bool: 如果添加成功返回True，否则返回False。
        """
        normalized = self._normalize(username)
        if normalized in self.usernames:
            return False  # 会员名已存在
        self.usernames.add(normalized)
        return True  # 添加成功
    
    def is_username_taken(self, username):
        """
        检查一个会员名是否已经被占用。

        参数:
            username (str): 用户输入的会员名。

        返回:
            bool: 如果已被占用返回True，否则返回False。
        """
        normalized = self._normalize(username)
        return normalized in self.usernames
    
    def _normalize(self, username):
        """
        标准化会员名（例如，转换为全小写）。

        参数:
            username (str): 原始会员名。

        返回:
            str: 标准化后的会员名。
        """
        return username.lower().strip()

# 示例用法
if __name__ == "__main__":
    manager = UsernameManager()
    
    # 预先添加一些会员名
    existing_usernames = ["Alice", "Bob", "CHARLIE", "dave"]
    for name in existing_usernames:
        manager.add_username(name)
    
    while True:
        new_username = input("请输入要注册的会员名（输入'退出'结束）：").strip()
        if new_username.lower() == '退出':
            break
        if manager.is_username_taken(new_username):
            print(f"抱歉，会员名 '{new_username}' 已被占用。请尝试其他名称。")
        else:
            manager.add_username(new_username)
            print(f"会员名 '{new_username}' 注册成功！")

请输入要注册的会员名（输入'退出'结束）： mraa

会员名 'mraa' 注册成功！

请输入要注册的会员名（输入'退出'结束）： MRAA

抱歉，会员名 'MRAA' 已被占用。请尝试其他名称。

请输入要注册的会员名（输入'退出'结束）： asas

会员名 'asas' 注册成功！

In [ ]:
import re

def normalize_greeting(s):
    """
    标准化问候语字符串。
    
    参数:
        s (str): 原始字符串。
        
    返回:
        str: 标准化后的字符串。
    """
    # 1. 转换为小写
    s = s.lower()
    
    # 2. 定义替换规则
    replacements = {
        '2': 'to',
        'u': 'you'
    }
    
    # 3. 进行替换
    for key, value in replacements.items():
        # 使用正则确保只替换独立的词
        s = re.sub(r'\b' + re.escape(key) + r'\b', value, s)
    
    # 4. 去除非字母字符（保留空格）
    s = re.sub(r'[^a-z\s]', '', s)
    
    # 5. 去除多余空格
    s = ' '.join(s.split())
    
    return s

# 测试字符串
str1 = '    haPPy BiRthDAy To u'
str2 = 'Happy biRthDAy To u'
str3 = '  haPpy BirThdAy 2 Dear friend'
str4 = '  happy birthday 2 u’'

# 应用标准化函数
normalized_str1 = normalize_greeting(str1)
normalized_str2 = normalize_greeting(str2)
normalized_str3 = normalize_greeting(str3)
normalized_str4 = normalize_greeting(str4)

# 输出结果
print(normalized_str1)  # 输出: happy birthday to you
print(normalized_str2)  # 输出: happy birthday to you
print(normalized_str3)  # 输出: happy birthday to dear friend
print(normalized_str4)  # 输出: happy birthday to you