In [1]:
import pandas as pd
import os
import numpy as np

In [2]:
# 使用相对路径直接读取文件
df = pd.read_csv('五粮液股票数据.csv', encoding='gbk')

# 显示前5行数据
print(df.head())

        股票代码      交易日期    开盘价    最高价    最低价    收盘价    昨收价   涨跌额     涨跌幅  \
0  000858.SZ  20180920  64.40  64.85  64.03  64.39  64.44 -0.05 -0.0776
1  000858.SZ  20180919  62.99  65.53  62.90  64.44  63.21  1.23  1.9459
2  000858.SZ  20180918  61.62  63.60  61.01  63.21  61.86  1.35  2.1823
3  000858.SZ  20180917  61.40  62.56  61.03  61.86  61.53  0.33  0.5363
4  000858.SZ  20180914  60.45  62.16  59.70  61.53  59.98  1.55  2.5842

      成交量（手）      成交额（千元）
0  164165.71  1056728.297
1  411364.31  2653606.009
2  263861.24  1647393.657
3  235508.59  1458775.764
4  294960.29  1800648.312

In [3]:
print(os.getcwd)

<built-in function getcwd>

In [4]:
current_directory = os.getcwd()

In [5]:
print(current_directory)

C:\Users\Administrator\Desktop\sjfxlx

In [6]:
average_close_price = df["收盘价"].mean()
print(f"收盘价的平均值:{average_close_price}")

收盘价的平均值:26.44052080607171

In [7]:
filtered_date = df[df["开盘价"] >60]
filtered_date

,股票代码,交易日期,开盘价,最高价,最低价,收盘价,昨收价,涨跌额,涨跌幅,成交量（手）,成交额（千元）
0,000858.SZ,20180920,64.40,64.85,64.03,64.39,64.44,-0.05,-0.0776,164165.71,1056728.297
1,000858.SZ,20180919,62.99,65.53,62.90,64.44,63.21,1.23,1.9459,411364.31,2653606.009
2,000858.SZ,20180918,61.62,63.60,61.01,63.21,61.86,1.35,2.1823,263861.24,1647393.657
3,000858.SZ,20180917,61.40,62.56,61.03,61.86,61.53,0.33,0.5363,235508.59,1458775.764
4,000858.SZ,20180914,60.45,62.16,59.70,61.53,59.98,1.55,2.5842,294960.29,1800648.312
...,...,...,...,...,...,...,...,...,...,...,...
229,000858.SZ,20171019,61.01,63.80,60.81,63.00,61.35,1.65,2.6900,278718.61,1744925.529
230,000858.SZ,20171018,60.12,61.35,59.17,61.35,60.10,1.25,2.0800,176535.50,1062478.441
232,000858.SZ,20171016,61.14,62.15,59.60,59.65,61.62,-1.97,-3.2000,270032.78,1635212.067
233,000858.SZ,20171013,60.86,61.95,60.85,61.62,60.81,0.81,1.3300,162023.88,995669.000
234,000858.SZ,20171012,61.36,61.95,60.46,60.81,61.18,-0.37,-0.6000,176004.66,1073412.431

In [8]:
df["价格差"] = df["最高价"] - df["最低价"]
df[['交易日期', '最高价', '最低价', '价格差']].head()

       交易日期    最高价    最低价   价格差
0  20180920  64.85  64.03  0.82
1  20180919  65.53  62.90  2.63
2  20180918  63.60  61.01  2.59
3  20180917  62.56  61.03  1.53
4  20180914  62.16  59.70  2.46

In [9]:
filtered_date.to_csv("筛选后的五粮液股票数据.csv", index=False, encoding="gbk")

In [10]:
new_one = pd.read_csv("五粮液股票数据.csv",encoding="gbk")
new_one.head()

,股票代码,交易日期,开盘价,最高价,最低价,收盘价,昨收价,涨跌额,涨跌幅,成交量（手）,成交额（千元）
0,000858.SZ,20180920,64.40,64.85,64.03,64.39,64.44,-0.05,-0.0776,164165.71,1056728.297
1,000858.SZ,20180919,62.99,65.53,62.90,64.44,63.21,1.23,1.9459,411364.31,2653606.009
2,000858.SZ,20180918,61.62,63.60,61.01,63.21,61.86,1.35,2.1823,263861.24,1647393.657
3,000858.SZ,20180917,61.40,62.56,61.03,61.86,61.53,0.33,0.5363,235508.59,1458775.764
4,000858.SZ,20180914,60.45,62.16,59.70,61.53,59.98,1.55,2.5842,294960.29,1800648.312

In [11]:
average_close_price = df["收盘价"].mean

In [12]:
print(f"平均收盘价:{average_close_price}")

平均收盘价:<bound method Series.mean of 0       64.39
1       64.44
2       63.21
3       61.86
4       61.53
        ...
3816    11.35
3817    11.12
3818    11.23
3819    11.18
3820    11.15
Name: 收盘价, Length: 3821, dtype: float64>

In [13]:
filtered_date = df[df["开盘价"] > 85]
filtered_date

,股票代码,交易日期,开盘价,最高价,最低价,收盘价,昨收价,涨跌额,涨跌幅,成交量（手）,成交额（千元）,价格差
69,000858.SZ,20180614,85.38,86.11,82.65,84.41,85.47,-1.06,-1.24,265874.16,2237838.346,3.46
70,000858.SZ,20180613,85.79,86.66,85.03,85.47,86.00,-0.53,-0.62,286972.53,2460756.755,1.63
158,000858.SZ,20180129,86.60,86.60,81.70,82.08,86.84,-4.76,-5.48,591383.27,4943911.228,4.90
159,000858.SZ,20180126,85.50,87.77,85.12,86.84,86.00,0.84,0.98,312053.75,2700119.273,2.65
160,000858.SZ,20180125,86.60,87.09,84.18,86.00,87.35,-1.35,-1.55,421128.92,3604252.895,2.91
161,000858.SZ,20180124,89.58,89.58,86.66,87.35,89.71,-2.36,-2.63,349695.75,3063373.440,2.92
162,000858.SZ,20180123,90.42,90.80,88.41,89.71,90.42,-0.71,-0.79,384681.66,3439974.330,2.39
163,000858.SZ,20180122,85.67,90.50,85.67,90.42,85.17,5.25,6.16,445823.53,3918907.687,4.83
164,000858.SZ,20180119,86.40,86.88,84.31,85.17,86.40,-1.23,-1.42,382003.65,3259552.587,2.57
165,000858.SZ,20180118,86.31,88.35,84.30,86.40,86.01,0.39,0.45,429700.90,3712081.698,4.05
166,000858.SZ,20180117,90.30,91.12,85.65,86.01,90.82,-4.81,-5.30,496108.96,4346534.429,5.47
167,000858.SZ,20180116,90.61,92.50,89.87,90.82,91.75,-0.93,-1.01,366155.22,3335555.956,2.63
168,000858.SZ,20180115,91.20,93.18,90.68,91.75,91.37,0.38,0.42,379644.08,3482483.788,2.50
169,000858.SZ,20180112,87.96,91.75,87.62,91.37,87.96,3.41,3.88,320923.56,2870276.321,4.13
170,000858.SZ,20180111,88.74,89.78,87.33,87.96,88.90,-0.94,-1.06,254778.62,2249762.450,2.45
171,000858.SZ,20180110,86.49,89.16,85.01,88.90,86.10,2.80,3.25,342458.66,2978674.635,4.15

In [14]:
max_high_price = df["最高价"].max()
print(f"最高价的最大值：{max_high_price}")

最高价的最大值：93.18

In [15]:
min_low_price = df["最低价"].min()
print(f"最底价的最小值：{min_low_price}")

最底价的最小值：5.95

In [16]:
df["交易日期"]  = pd.to_datetime(df["交易日期"],format="%Y%m%d")
september_data = df[(df["交易日期"] >= "2018-09-01") & (df["交易日期"] <= "2018-09-30")]
september_data

,股票代码,交易日期,开盘价,最高价,最低价,收盘价,昨收价,涨跌额,涨跌幅,成交量（手）,成交额（千元）,价格差
0,000858.SZ,2018-09-20,64.40,64.85,64.03,64.39,64.44,-0.05,-0.0776,164165.71,1056728.297,0.82
1,000858.SZ,2018-09-19,62.99,65.53,62.90,64.44,63.21,1.23,1.9459,411364.31,2653606.009,2.63
2,000858.SZ,2018-09-18,61.62,63.60,61.01,63.21,61.86,1.35,2.1823,263861.24,1647393.657,2.59
3,000858.SZ,2018-09-17,61.40,62.56,61.03,61.86,61.53,0.33,0.5363,235508.59,1458775.764,1.53
4,000858.SZ,2018-09-14,60.45,62.16,59.70,61.53,59.98,1.55,2.5842,294960.29,1800648.312,2.46
5,000858.SZ,2018-09-13,60.39,60.65,58.58,59.98,59.65,0.33,0.5532,206865.36,1232442.100,2.07
6,000858.SZ,2018-09-12,61.00,61.00,59.59,59.65,61.00,-1.35,-2.2131,191607.79,1150744.732,1.41
7,000858.SZ,2018-09-11,60.38,61.35,60.20,61.00,60.38,0.62,1.0268,202919.36,1235001.569,1.15
8,000858.SZ,2018-09-10,60.92,60.96,59.28,60.38,60.77,-0.39,-0.6418,195919.16,1179507.359,1.68
9,000858.SZ,2018-09-07,60.30,61.15,59.80,60.77,59.71,1.06,1.7752,222726.04,1347995.371,1.35
10,000858.SZ,2018-09-06,60.50,61.64,59.18,59.71,60.90,-1.19,-1.9540,319221.95,1924316.865,2.46
11,000858.SZ,2018-09-05,62.75,62.75,60.80,60.90,62.77,-1.87,-2.9791,217130.48,1342662.987,1.95
12,000858.SZ,2018-09-04,62.27,62.96,61.60,62.77,61.97,0.80,1.2909,194838.65,1215148.333,1.36
13,000858.SZ,2018-09-03,61.10,62.17,61.09,61.97,61.90,0.07,0.1131,208324.53,1283847.415,1.08

In [17]:
df["月份"] = df["交易日期"].dt.to_period("M")
mothly_avg_close_price = df.groupby("月份")["收盘价"].mean()
mothly_avg_close_price

月份
2003-01    11.813500
2003-02    12.016000
2003-03    11.285714
2003-04    10.748636
2003-05     9.534000
             ...
2018-05    76.451818
2018-06    81.048500
2018-07    73.286364
2018-08    64.418696
2018-09    61.611429
Freq: M, Name: 收盘价, Length: 189, dtype: float64

In [18]:
!pip install matplotlib

Requirement already satisfied: matplotlib in e:\software\python\python2\lib\site-packages (3.9.2)
Requirement already satisfied: contourpy>=1.0.1 in e:\software\python\python2\lib\site-packages (from matplotlib) (1.3.0)
Requirement already satisfied: cycler>=0.10 in e:\software\python\python2\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in e:\software\python\python2\lib\site-packages (from matplotlib) (4.54.1)
Requirement already satisfied: kiwisolver>=1.3.1 in e:\software\python\python2\lib\site-packages (from matplotlib) (1.4.7)
Requirement already satisfied: numpy>=1.23 in e:\software\python\python2\lib\site-packages (from matplotlib) (2.1.2)
Requirement already satisfied: packaging>=20.0 in e:\software\python\python2\lib\site-packages (from matplotlib) (24.1)
Requirement already satisfied: pillow>=8 in e:\software\python\python2\lib\site-packages (from matplotlib) (11.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in e:\software\python\python2\lib\site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in e:\software\python\python2\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in e:\software\python\python2\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [19]:
import matplotlib.pyplot as plt

In [20]:
print(df.dtypes)

股票代码               object
交易日期       datetime64[ns]
开盘价               float64
最高价               float64
最低价               float64
收盘价               float64
昨收价               float64
涨跌额               float64
涨跌幅               float64
成交量（手）            float64
成交额（千元）           float64
价格差               float64
月份              period[M]
dtype: object

In [21]:
filtered_date = df[df["开盘价"] >90 ]
filtered_date

,股票代码,交易日期,开盘价,最高价,最低价,收盘价,昨收价,涨跌额,涨跌幅,成交量（手）,成交额（千元）,价格差,月份
162,000858.SZ,2018-01-23,90.42,90.80,88.41,89.71,90.42,-0.71,-0.79,384681.66,3439974.330,2.39,2018-01
166,000858.SZ,2018-01-17,90.30,91.12,85.65,86.01,90.82,-4.81,-5.30,496108.96,4346534.429,5.47,2018-01
167,000858.SZ,2018-01-16,90.61,92.50,89.87,90.82,91.75,-0.93,-1.01,366155.22,3335555.956,2.63,2018-01
168,000858.SZ,2018-01-15,91.20,93.18,90.68,91.75,91.37,0.38,0.42,379644.08,3482483.788,2.50,2018-01

In [22]:
# 使用循环逐行检查开盘价
for index, row in df.iterrows():
    if row['开盘价'] > 90:
        print(f"第 {index} 行的开盘价大于 90: {row['开盘价']}")

第 162 行的开盘价大于 90: 90.42
第 166 行的开盘价大于 90: 90.3
第 167 行的开盘价大于 90: 90.61
第 168 行的开盘价大于 90: 91.2

In [23]:
arry = np.array([[1,2],[3,4]])
arry

array([[1, 2],
       [3, 4]])

In [24]:
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])
matrix_sum = matrix1 + matrix2
matrix_sum

array([[ 6,  8],
       [10, 12]])

In [25]:
my_list = [1,2,3,4]
my_list[0]

1

In [27]:
cleaned_df = df.dropna()
filed_df = df.fillna(0)

In [28]:
filtered_df = df[df["开盘价"] >90 ]
filtered_df

,股票代码,交易日期,开盘价,最高价,最低价,收盘价,昨收价,涨跌额,涨跌幅,成交量（手）,成交额（千元）,价格差,月份
162,000858.SZ,2018-01-23,90.42,90.80,88.41,89.71,90.42,-0.71,-0.79,384681.66,3439974.330,2.39,2018-01
166,000858.SZ,2018-01-17,90.30,91.12,85.65,86.01,90.82,-4.81,-5.30,496108.96,4346534.429,5.47,2018-01
167,000858.SZ,2018-01-16,90.61,92.50,89.87,90.82,91.75,-0.93,-1.01,366155.22,3335555.956,2.63,2018-01
168,000858.SZ,2018-01-15,91.20,93.18,90.68,91.75,91.37,0.38,0.42,379644.08,3482483.788,2.50,2018-01

In [29]:
matrix = np.array([[1,2],[3,4]])
transposed_matrix = matrix.T
transposed_matrix

array([[1, 3],
       [2, 4]])

In [30]:
new_matrix = matrix + 10
new_matrix

array([[11, 12],
       [13, 14]])

In [32]:
df = df.rename(columns={"旧列名":"新列名","开盘价":"open price"})
df.head()

,股票代码,交易日期,open price,最高价,最低价,收盘价,昨收价,涨跌额,涨跌幅,成交量（手）,成交额（千元）,价格差,月份
0,000858.SZ,2018-09-20,64.40,64.85,64.03,64.39,64.44,-0.05,-0.0776,164165.71,1056728.297,0.82,2018-09
1,000858.SZ,2018-09-19,62.99,65.53,62.90,64.44,63.21,1.23,1.9459,411364.31,2653606.009,2.63,2018-09
2,000858.SZ,2018-09-18,61.62,63.60,61.01,63.21,61.86,1.35,2.1823,263861.24,1647393.657,2.59,2018-09
3,000858.SZ,2018-09-17,61.40,62.56,61.03,61.86,61.53,0.33,0.5363,235508.59,1458775.764,1.53,2018-09
4,000858.SZ,2018-09-14,60.45,62.16,59.70,61.53,59.98,1.55,2.5842,294960.29,1800648.312,2.46,2018-09

In [33]:
df = df.drop(columns=["昨收价"])
df.head()

,股票代码,交易日期,open price,最高价,最低价,收盘价,涨跌额,涨跌幅,成交量（手）,成交额（千元）,价格差,月份
0,000858.SZ,2018-09-20,64.40,64.85,64.03,64.39,-0.05,-0.0776,164165.71,1056728.297,0.82,2018-09
1,000858.SZ,2018-09-19,62.99,65.53,62.90,64.44,1.23,1.9459,411364.31,2653606.009,2.63,2018-09
2,000858.SZ,2018-09-18,61.62,63.60,61.01,63.21,1.35,2.1823,263861.24,1647393.657,2.59,2018-09
3,000858.SZ,2018-09-17,61.40,62.56,61.03,61.86,0.33,0.5363,235508.59,1458775.764,1.53,2018-09
4,000858.SZ,2018-09-14,60.45,62.16,59.70,61.53,1.55,2.5842,294960.29,1800648.312,2.46,2018-09

In [34]:
cleaned_df = df.dropna()

In [35]:
matrix = np.array([[1,2,3],[4,5,6]])

In [36]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
transposed_matrix = matrix.T

In [38]:
transposed_matrix

array([[1, 4],
       [2, 5],
       [3, 6]])

In [39]:
new_matrix = matrix + 20
new_matrix

array([[21, 22, 23],
       [24, 25, 26]])

In [42]:
matrix = np.array([[1,2,3],[4,5,6]])
vector = np.array([1,0,1])
new_matrix = matrix + vector
new_matrix

array([[2, 2, 4],
       [5, 5, 7]])

In [49]:
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])

In [48]:
product_matrix = np.dot(matrix1,matrix2)
product_matrix

array([[19, 22],
       [43, 50]])