In [2]:
import numpy as np
import pandas as pd

In [3]:
jz = pd.read_csv("五粮液股票数据.csv", encoding="gbk")
jz.head()

,股票代码,交易日期,开盘价,最高价,最低价,收盘价,昨收价,涨跌额,涨跌幅,成交量（手）,成交额（千元）
0,000858.SZ,20180920,64.40,64.85,64.03,64.39,64.44,-0.05,-0.0776,164165.71,1056728.297
1,000858.SZ,20180919,62.99,65.53,62.90,64.44,63.21,1.23,1.9459,411364.31,2653606.009
2,000858.SZ,20180918,61.62,63.60,61.01,63.21,61.86,1.35,2.1823,263861.24,1647393.657
3,000858.SZ,20180917,61.40,62.56,61.03,61.86,61.53,0.33,0.5363,235508.59,1458775.764
4,000858.SZ,20180914,60.45,62.16,59.70,61.53,59.98,1.55,2.5842,294960.29,1800648.312

In [4]:
jz_cleaned = jz.dropna

In [7]:
jz_filled = jz.fillna(0)

In [11]:
jz = jz.rename(columns={"开盘价":"open price","收盘价":"clouse price","最高价":"high price","最低价":"low price"})

In [12]:
jz

,股票代码,交易日期,open price,high price,low price,clouse price,昨收价,涨跌额,涨跌幅,成交量（手）,成交额（千元）
0,000858.SZ,20180920,64.40,64.85,64.03,64.39,64.44,-0.05,-0.0776,164165.71,1.056728e+06
1,000858.SZ,20180919,62.99,65.53,62.90,64.44,63.21,1.23,1.9459,411364.31,2.653606e+06
2,000858.SZ,20180918,61.62,63.60,61.01,63.21,61.86,1.35,2.1823,263861.24,1.647394e+06
3,000858.SZ,20180917,61.40,62.56,61.03,61.86,61.53,0.33,0.5363,235508.59,1.458776e+06
4,000858.SZ,20180914,60.45,62.16,59.70,61.53,59.98,1.55,2.5842,294960.29,1.800648e+06
...,...,...,...,...,...,...,...,...,...,...,...
3816,000858.SZ,20030108,11.12,11.37,11.10,11.35,11.12,0.23,2.0700,3722.07,4.183312e+03
3817,000858.SZ,20030107,11.10,11.28,11.10,11.12,11.23,-0.11,-0.9800,3861.13,4.303665e+03
3818,000858.SZ,20030106,11.18,11.28,11.00,11.23,11.18,0.05,0.4500,4205.45,4.692610e+03
3819,000858.SZ,20030103,11.14,11.30,11.11,11.18,11.15,0.03,0.2700,4821.27,5.379806e+03
3820,000858.SZ,20030102,11.45,11.46,11.10,11.15,11.59,-0.44,-3.8000,6501.25,7.293120e+03

In [13]:
jz["交易日期"] = pd.to_datetime(jz["交易日期"],format="%Y%m%d")

In [17]:
filltered_jz = jz[(jz["交易日期"] >= "2018-01-01") & (jz["交易日期"] <= "2018-12-31")]

In [18]:
filltered_jz

,股票代码,交易日期,open price,high price,low price,clouse price,昨收价,涨跌额,涨跌幅,成交量（手）,成交额（千元）
0,000858.SZ,2018-09-20,64.40,64.85,64.03,64.39,64.44,-0.05,-0.0776,164165.71,1056728.297
1,000858.SZ,2018-09-19,62.99,65.53,62.90,64.44,63.21,1.23,1.9459,411364.31,2653606.009
2,000858.SZ,2018-09-18,61.62,63.60,61.01,63.21,61.86,1.35,2.1823,263861.24,1647393.657
3,000858.SZ,2018-09-17,61.40,62.56,61.03,61.86,61.53,0.33,0.5363,235508.59,1458775.764
4,000858.SZ,2018-09-14,60.45,62.16,59.70,61.53,59.98,1.55,2.5842,294960.29,1800648.312
...,...,...,...,...,...,...,...,...,...,...,...
173,000858.SZ,2018-01-08,82.59,83.61,81.60,82.20,82.68,-0.48,-0.5800,286818.34,2367460.141
174,000858.SZ,2018-01-05,82.77,83.45,81.40,82.68,82.99,-0.31,-0.3700,231958.09,1913069.874
175,000858.SZ,2018-01-04,80.79,83.61,80.60,82.99,80.90,2.09,2.5800,360577.06,2979263.417
176,000858.SZ,2018-01-03,80.50,81.76,79.85,80.90,80.58,0.32,0.4000,284614.26,2303523.783
177,000858.SZ,2018-01-02,80.20,81.00,78.33,80.58,79.88,0.70,0.8800,315252.33,2515564.441

In [19]:
average_open_prince = filltered_jz["open price"].mean()
average_open_prince

np.float64(73.91932584269662)

In [20]:
max_high_price = filltered_jz["high price"].max()

In [21]:
max_high_price

np.float64(93.18)

In [22]:
print(f"2018年开盘价平均值:{average_open_prince}")
print(f"2018年最高价最大值：{max_high_price}")

2018年开盘价平均值:73.91932584269662
2018年最高价最大值：93.18

In [23]:
oepn_price = filltered_jz["open price"].values
high_price = filltered_jz["high price"].values
low_price = filltered_jz["low price"].values

In [25]:
oepn_price

array([64.4 , 62.99, 61.62, 61.4 , 60.45, 60.39, 61.  , 60.38, 60.92,
       60.3 , 60.5 , 62.75, 62.27, 61.1 , 62.99, 63.7 , 64.29, 66.03,
       63.1 , 63.9 , 63.98, 63.99, 62.05, 60.99, 61.85, 62.33, 65.11,
       64.99, 65.25, 66.26, 64.1 , 66.6 , 65.  , 65.09, 68.  , 70.  ,
       72.8 , 72.4 , 74.24, 74.  , 75.11, 75.14, 72.25, 73.  , 73.18,
       73.98, 74.38, 75.5 , 75.63, 74.25, 72.  , 71.2 , 73.57, 71.58,
       69.9 , 71.69, 72.08, 73.6 , 76.01, 74.  , 75.22, 81.  , 81.9 ,
       81.02, 80.4 , 81.7 , 80.  , 82.  , 84.  , 85.38, 85.79, 82.83,
       80.35, 80.33, 82.4 , 82.75, 82.  , 78.88, 78.64, 77.79, 75.65,
       77.5 , 74.88, 74.02, 76.4 , 77.5 , 76.9 , 78.1 , 76.91, 79.4 ,
       79.43, 78.31, 77.66, 78.55, 76.37, 75.8 , 75.8 , 73.28, 73.55,
       71.29, 69.2 , 69.97, 71.9 , 71.91, 70.  , 69.3 , 70.  , 67.3 ,
       67.6 , 68.4 , 67.7 , 69.89, 70.29, 70.76, 69.75, 69.89, 67.48,
       65.9 , 65.9 , 67.25, 65.5 , 67.1 , 71.  , 70.53, 70.  , 74.08,
       76.32, 76.56, 76.34, 78.2 , 75.68, 74.  , 76.24, 77.6 , 77.3 ,
       73.79, 73.24, 72.76, 73.81, 73.8 , 73.8 , 74.  , 78.99, 79.6 ,
       80.01, 77.8 , 76.1 , 75.09, 72.  , 69.22, 70.85, 77.59, 76.  ,
       79.31, 82.15, 83.6 , 81.32, 81.1 , 86.6 , 85.5 , 86.6 , 89.58,
       90.42, 85.67, 86.4 , 86.31, 90.3 , 90.61, 91.2 , 87.96, 88.74,
       86.49, 82.4 , 82.59, 82.77, 80.79, 80.5 , 80.2 ])

In [26]:
increased_open_price = oepn_price * 1.01

In [28]:
price_difference = high_price - low_price
print("每日差价：",price_difference)

每日差价： [0.82 2.63 2.59 1.53 2.46 2.07 1.41 1.15 1.68 1.35 2.46 1.95 1.36 1.08
 1.36 1.38 1.17 2.21 2.21 1.4  1.65 1.09 2.76 2.57 2.   2.27 1.83 1.81
 2.15 1.85 2.68 2.36 2.67 2.12 2.34 3.4  2.82 1.23 2.47 1.59 1.28 0.98
 3.56 3.09 2.33 1.16 1.62 2.52 1.79 2.39 2.79 1.71 2.05 3.15 3.1  3.01
 2.42 5.32 4.23 3.38 2.67 5.31 2.88 2.65 1.67 2.56 2.61 3.44 1.9  3.46
 1.63 4.31 3.5  2.36 2.34 1.8  3.11 4.23 2.16 2.74 3.98 3.03 3.19 1.65
 2.98 1.81 1.93 2.44 2.48 3.04 1.16 2.02 1.68 2.35 1.84 1.52 1.52 3.2
 1.14 3.48 3.24 3.17 3.11 0.95 2.6  1.82 2.47 4.08 2.79 2.15 1.97 2.72
 1.55 1.39 1.13 1.74 3.25 1.81 2.79 1.74 3.97 3.5  4.25 1.9  2.68 2.61
 2.4  2.32 2.15 1.92 2.61 2.57 2.49 2.34 2.21 3.66 2.08 3.29 2.47 2.3
 1.93 2.78 3.2  2.95 2.46 2.63 2.14 1.95 3.   4.47 3.03 7.98 2.85 4.53
 3.15 2.67 3.77 2.96 4.9  2.65 2.91 2.92 2.39 4.83 2.57 4.05 5.47 2.63
 2.5  4.13 2.45 4.15 3.74 2.01 2.05 3.01 1.91 2.67]